application:
  name: GEDX
  project: GEDX
  publicly_accessible: true
databases:
- type: postgresql
  version: "12"
  name: gedx
routers:
- name: main
  routes:
  - application_name: GEDX
    paths:
    - /
